title: B-fresh
description: B-Fresh is a food and lifestyle blog by Bridget Sexton. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justbfresh.wordpress.com" # the base hostname & protocol for your site

collections: 
  blog_tags: 
    title: Tags
    output: True
  posts: 
    title: Posts
    output: True

defaults: 
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"

markdown: kramdown